/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'outline':                    '#988d9f',
        'surface-container-high':     '#2a2a2a',
        'primary-fixed-dim':          '#ddb7ff',
        'error-container':            '#93000a',
        'on-primary-fixed-variant':   '#6900b3',
        'on-tertiary-fixed-variant':  '#85145a',
        'on-tertiary':                '#620040',
        'inverse-on-surface':         '#313030',
        'on-secondary-container':     '#e6ecff',
        'secondary-container':        '#0566d9',
        'on-primary-container':       '#400071',
        'background':                 '#131313',
        'on-background':              '#e5e2e1',
        'on-surface-variant':         '#cfc2d6',
        'on-surface':                 '#e5e2e1',
        'tertiary':                   '#ffafd3',
        'primary':                    '#ddb7ff',
        'inverse-primary':            '#842bd2',
        'surface-dim':                '#131313',
        'surface-bright':             '#3a3939',
        'on-primary-fixed':           '#2c0051',
        'error':                      '#ffb4ab',
        'on-tertiary-container':      '#560038',
        'tertiary-container':         '#e364a7',
        'on-tertiary-fixed':          '#3d0026',
        'on-primary':                 '#490080',
        'on-error-container':         '#ffdad6',
        'outline-variant':            '#4d4354',
        'surface-container-highest':  '#353534',
        'surface-container-low':      '#1c1b1b',
        'surface-container':          '#201f1f',
        'inverse-surface':            '#e5e2e1',
        'on-secondary-fixed-variant': '#004395',
        'tertiary-fixed-dim':         '#ffafd3',
        'primary-fixed':              '#f0dbff',
        'tertiary-fixed':             '#ffd8e7',
        'on-secondary-fixed':         '#001a42',
        'on-secondary':               '#002e6a',
        'on-error':                   '#690005',
        'secondary-fixed-dim':        '#adc6ff',
        'secondary':                  '#adc6ff',
        'surface-tint':               '#ddb7ff',
        'surface-container-lowest':   '#0e0e0e',
        'surface-variant':            '#353534',
        'secondary-fixed':            '#d8e2ff',
        'primary-container':          '#b76dff',
        'surface':                    '#131313',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Geist', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display':    ['72px', { lineHeight: '1.1',  letterSpacing: '-0.04em', fontWeight: '700' }],
        'headline-lg':['40px', { lineHeight: '1.2',  letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md':['24px', { lineHeight: '1.4',  fontWeight: '500' }],
        'headline-sm':['20px', { lineHeight: '1.4',  fontWeight: '600' }],
        'body-lg':    ['18px', { lineHeight: '1.6',  fontWeight: '400' }],
        'body-md':    ['16px', { lineHeight: '1.6',  fontWeight: '400' }],
        'body-sm':    ['14px', { lineHeight: '1.5',  fontWeight: '400' }],
        'label-sm':   ['13px', { lineHeight: '1',    letterSpacing: '0.02em', fontWeight: '500' }],
        'label-xs':   ['11px', { lineHeight: '1',    letterSpacing: '0.04em', fontWeight: '600' }],
      },
      backdropBlur: {
        '2xl': '40px',
        '3xl': '64px',
      },
      keyframes: {
        scan: {
          '0%':   { top: '0%' },
          '100%': { top: '100%' },
        },
        'fade-up': {
          '0%':   { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'pulse-glow': {
          '0%,100%': { opacity: '1' },
          '50%':     { opacity: '0.5' },
        },
        shimmer: {
          '0%':   { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
      animation: {
        scan:        'scan 3s ease-in-out infinite alternate',
        'fade-up':   'fade-up 0.3s ease both',
        'pulse-glow':'pulse-glow 2s ease infinite',
        shimmer:     'shimmer 1.8s infinite',
      },
    },
  },
  plugins: [],
}
